
data = {
  "civs" : [
    "athen",
    "brit",
    "cart",
    "celt",
    "gaul",
    "hele",
    "iber",
    "mace",
    "maur",
    "pers",
    "ptol",
    "rome",
    "sele",
    "theb",
  ],
  "pathMaps": "/home/noiv/.local/share/0ad/mods/public/maps/scenarios/",
  "testMaps": [
    "Arcadia 02.xml",
    "Azure Coast.xml",
    "Barcania.xml",
    "Battle for the Tiber.xml",
    "Belgian_Bog_night.xml",
    "Eire and Albion.xml",
    "Gold_Rush.xml",
    "Gorge.xml",
  ],
  "mapsAll": [
    "Abyss39.xml",
    "Arcadia 02.xml",
    "Azure Coast.xml",
    "Azure Coast(2).xml",
    "Azure Coast(4).xml",
    "Barcania.xml",
    "Battle for the Tiber.xml",
    "Belgian_Bog_night.xml",
    "Bridge_demo.xml",
    "Campaign Test Map.xml",
    "Campaign Test Map 2 - heightmap.xml",
    "Combat_demo.xml",
    "Combat_demo_(huge).xml",
    "Death Canyon - Invasion Force.xml",
    "Demo_Trading.xml",
    "Eire and Albion.xml",
    "Fast Oasis.xml",
    "Fishing_demo.xml",
    "Flight_demo.xml",
    "Flight_demo_2.xml",
    "Gold_Rush.xml",
    "Gorge.xml",
    "Height Map Import - Demo (Fractal).xml",
    "Height Map Import - Demo (Greece).xml",
    "Height Map Import - Demo (Greece-Small).xml",
    "Introductory Tutorial.xml",
    "Laconia 01.xml",
    "Migration.xml",
    "Miletus.xml",
    "Multiplayer_demo.xml",
    "Necropolis.xml",
    "Pathfinding_demo.xml",
    "Pathfinding_terrain_demo.xml",
    "Peloponnese.xml",
    "Polynesia.xml",
    "reservoir.xml",
    "Resource_demo.xml",
    "road demo.xml",
    "Saharan Oases.xml",
    "Sahel.xml",
    "Sandbox - Athenians.xml",
    "Sandbox - Britons.xml",
    "Sandbox - Carthaginians.xml",
    "Sandbox - Gauls.xml",
    "Sandbox - Iberians.xml",
    "Sandbox - Macedonians.xml",
    "Sandbox - Mauryans.xml",
    "Sandbox - Persians.xml",
    "Sandbox - Ptolemies.xml",
    "Sandbox - Ptolemies 2.xml",
    "Sandbox - Romans.xml",
    "Sandbox - Seleucids.xml",
    "Sandbox - Spartans.xml",
    "Savanna Ravine.xml",
    "Serengeti.xml",
    "shipattacks.xml",
    "Ship Formations.xml",
    "Siwa Oasis.xml",
    "starting_economy_walkthrough.xml",
    "temperate map.xml",
    "Territory Demo.xml",
    "The Massacre of Delphi.xml",
    "The Persian Gates.xml",
    "Third Macedonian War.xml",
    "Tropical Island.xml",
    "Units_demo.xml",
    "Walls.xml",
    "WallTest.xml",
    "We are Legion.xml"
  ]
}
